# Generated by Django 5.1.2 on 2024-11-25 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='houses',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_days', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cart')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.house')),
            ],
            options={
                'unique_together': {('cart', 'house')},
            },
        ),
    ]
